In [1]:
import numpy as np
array1 = np.array(range(30))
a = np.reshape(array1, (5, 6), order = 'F')
print(a)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [2]:
import numpy as np
array1 = np.array(range(30))
a = np.reshape(array1, (5, 6), order = 'F')
a = a[a % 6 == 1]
print(a)

[25  1  7 13 19]
